all:
	g++ -g -I/opt/local/include main.cc -L/opt/local/lib -lboost_thread-mt -lboost_system-mt -o out
	g++ -g -I/opt/local/include main2.cc -L/opt/local/lib -lboost_thread-mt -lboost_system-mt -o out2
